# ```Are Prices Justified? - IPL 2026```

## 1.Data Import

### 1.1 Data Import

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler,MinMaxScaler

import warnings
warnings.filterwarnings('ignore')

In [2]:
batters = pd.read_excel(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Are Prices Justified - IPL 2026\_dataset\IPL_2026_Combined_Data.xlsx",
                        sheet_name="Batting Stats",)

bowlers = pd.read_excel(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Are Prices Justified - IPL 2026\_dataset\IPL_2026_Combined_Data.xlsx",
                        sheet_name="Bowling Stats",)

prices = pd.read_excel(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Are Prices Justified - IPL 2026\_dataset\IPL_2026_Combined_Data.xlsx",
                        sheet_name="Auction Prices",)

In [3]:
batters.head()

,POS,Player,Team,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Vaibhav Sooryavanshi,RR,776,16,16,0,103,48.5,327,237.30,1,5,63,72
1,2,Shubman Gill,GT,732,16,16,0,104,45.75,449,163.02,1,6,74,33
2,3,Sai Sudharsan,GT,722,17,17,1,100,45.13,457,157.98,1,8,75,30
3,4,Virat Kohli,RCB,675,16,16,4,105*,56.25,407,165.84,1,5,73,25
4,5,Heinrich Klaasen,SRH,624,15,15,2,69,48,390,160.00,0,6,48,31

In [4]:
bowlers.head()

,POS,Player,Team,Wkts,Mat,Inns,Ov,Runs,BBI,Avg,Econ,SR,4w,5w
0,1,Kagiso Rabada,GT,29,17,17,64.4,626,25/3,21.58,9.68,13.37,0,0
1,2,Bhuvneshwar Kumar,RCB,28,16,16,63.0,501,23/4,17.89,7.95,13.50,1,0
2,3,Jofra Archer,RR,25,16,16,60.0,559,17/3,22.36,9.31,14.40,0,0
3,4,Rashid Khan,GT,21,17,17,56.5,516,33/4,24.57,9.07,16.23,1,0
4,5,Anshul Kamboj,CSK,21,14,14,50.2,530,22/3,25.23,10.52,14.38,0,0

In [5]:
prices.head()

,Player,Auction_Year,Base_Price,Final_Price,Currency,Auction_Team,Role,Matched_Name_In_Auction
0,Abdul Samad,2025,3000000,42000000,INR,Lucknow Super Giants,Uncapped,Abdul Samad
1,Abhinandan Singh,2025,3000000,3000000,INR,Royal Challengers Bengaluru,Uncapped,Abhinandan Singh
2,Abhishek Sharma,2022,2000000,65000000,INR,Sunrisers Hyderabad,Capped,Abhishek Sharma
3,Adam Milne,2026,20000000,24000000,INR,Rajasthan Royals,Capped,Adam Milne
4,Aiden Markram,2025,20000000,20000000,INR,Lucknow Super Giants,Capped,Aiden Markram

### 1.2 Data Overview

In [6]:
batters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   POS     167 non-null    int64
 1   Player  167 non-null    object
 2   Team    167 non-null    object
 3   Runs    167 non-null    int64
 4   Mat     167 non-null    int64
 5   Inns    167 non-null    int64
 6   NO      167 non-null    int64
 7   HS      167 non-null    object
 8   Avg     167 non-null    object
 9   BF      167 non-null    int64
 10  SR      167 non-null    float64
 11  100     167 non-null    int64
 12  50      167 non-null    int64
 13  4s      167 non-null    int64
 14  6s      167 non-null    int64
dtypes: float64(1), int64(10), object(4)
memory usage: 19.7+ KB

In [7]:
bowlers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   POS     104 non-null    int64
 1   Player  104 non-null    object
 2   Team    104 non-null    object
 3   Wkts    104 non-null    int64
 4   Mat     104 non-null    int64
 5   Inns    104 non-null    int64
 6   Ov      104 non-null    float64
 7   Runs    104 non-null    int64
 8   BBI     104 non-null    object
 9   Avg     104 non-null    float64
 10  Econ    104 non-null    float64
 11  SR      104 non-null    float64
 12  4w      104 non-null    int64
 13  5w      104 non-null    int64
dtypes: float64(4), int64(7), object(3)
memory usage: 11.5+ KB

In [8]:
prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Player                   173 non-null    object
 1   Auction_Year             173 non-null    int64
 2   Base_Price               173 non-null    int64
 3   Final_Price              173 non-null    int64
 4   Currency                 173 non-null    object
 5   Auction_Team             173 non-null    object
 6   Role                     173 non-null    object
 7   Matched_Name_In_Auction  173 non-null    object
dtypes: int64(3), object(5)
memory usage: 10.9+ KB

In [9]:
batters.describe().reset_index().T

           0           1           2      3        4       5       6      7
index  count        mean         std    min      25%     50%     75%    max
POS    167.0        84.0    48.35287    1.0     42.5    84.0   125.5  167.0
Runs   167.0  156.592814  185.535732    1.0     12.5    65.0   266.0  776.0
Mat    167.0    9.628743    4.757355    1.0      6.0    10.0    14.0   17.0
Inns   167.0    6.736527    4.974881    1.0      2.0     5.0    11.0   17.0
NO     167.0    1.526946    1.508268    0.0      0.0     1.0     2.0    8.0
BF     167.0  100.065868  109.868988    1.0     12.0    52.0   168.5  457.0
SR     167.0  135.634491   48.185031  16.66  114.155  139.65  163.15  350.0
100    167.0     0.08982    0.307072    0.0      0.0     0.0     0.0    2.0
50     167.0    0.922156    1.624341    0.0      0.0     0.0     1.0    8.0
4s     167.0   13.964072   17.654615    0.0      1.0     5.0    22.5   75.0
6s     167.0    8.538922   11.384701    0.0      0.0     3.0    12.0   72.0

In [10]:
bowlers.describe().reset_index().T

           0           1           2     3        4       5       6      7
index  count        mean         std   min      25%     50%     75%    max
POS    104.0        52.5   30.166206   1.0    26.75    52.5   78.25  104.0
Wkts   104.0    8.028846     6.43633   1.0      2.0     6.0    12.0   29.0
Mat    104.0       8.875    4.771858   1.0     4.75     9.0    13.0   17.0
Inns   104.0    7.788462    4.618816   1.0     3.75     7.0    12.0   17.0
Ov     104.0   25.691346   17.521039   1.0     9.85    24.2  39.375   64.4
Runs   104.0  249.692308  159.631802   7.0    101.0   249.0   382.0  626.0
Avg    104.0   38.853558   22.289444   7.0     25.0   32.72   44.85  141.0
Econ   104.0   10.117308    1.549985  6.64      9.0    9.96    11.2   14.0
SR     104.0   23.002981   12.988723   6.0  15.3675  19.685    24.0   90.0
4w     104.0    0.163462    0.371577   0.0      0.0     0.0     0.0    1.0
5w     104.0    0.009615    0.098058   0.0      0.0     0.0     0.0    1.0

In [11]:
prices.describe().reset_index().T

,0,1,2,3,4,5,6,7
index,count,mean,std,min,25%,50%,75%,max
Auction_Year,173.0,2024.398844,2.030981,2014.0,2025.0,2025.0,2025.0,2026.0
Base_Price,173.0,9734104.046243,7695426.301762,1000000.0,3000000.0,5000000.0,20000000.0,20000000.0
Final_Price,173.0,41846820.809249,52245935.123481,1000000.0,5500000.0,20000000.0,57500000.0,270000000.0

## 2.Data Cleaning

In [12]:
batters.columns = batters.columns.str.lower()
bowlers.columns = bowlers.columns.str.lower()
prices.columns = prices.columns.str.lower()

In [13]:
batters.head()

,pos,player,team,runs,mat,inns,no,hs,avg,bf,sr,100,50,4s,6s
0,1,Vaibhav Sooryavanshi,RR,776,16,16,0,103,48.5,327,237.30,1,5,63,72
1,2,Shubman Gill,GT,732,16,16,0,104,45.75,449,163.02,1,6,74,33
2,3,Sai Sudharsan,GT,722,17,17,1,100,45.13,457,157.98,1,8,75,30
3,4,Virat Kohli,RCB,675,16,16,4,105*,56.25,407,165.84,1,5,73,25
4,5,Heinrich Klaasen,SRH,624,15,15,2,69,48,390,160.00,0,6,48,31

In [14]:
batters[batters['avg'].str.contains("-",na=False)].head()

,pos,player,team,runs,mat,inns,no,hs,avg,bf,sr,100,50,4s,6s
90,91,Shahbaz Ahamad,LSG,58,5,2,2,43*,-,41,141.46,0,0,4,3
101,102,Bhuvneshwar Kumar,RCB,34,16,4,4,15*,-,26,130.76,0,0,3,1
108,109,Mitchell Santner,MI,26,4,2,2,18*,-,19,136.84,0,0,3,0
114,115,Madhav Tiwari,DC,18,3,1,1,18*,-,8,225.00,0,0,2,1
119,120,Vishnu Vinod,PBKS,15,1,1,1,15*,-,8,187.50,0,0,1,1

In [15]:
mask = batters['avg'].astype(str).str.contains('-', na=False)
batters.loc[mask & (batters['inns'] > batters['no']), 'avg'] = (
    batters['runs'] / (batters['inns'] - batters['no'])
)
batters.loc[mask & (batters['inns'] == batters['no']), 'avg'] = batters['runs']

In [16]:
batters['avg'] = batters['avg'].astype(float)

In [17]:
batters['avg'].describe()

count    167.000000
mean      21.637605
std       15.916652
min        1.000000
25%        7.000000
50%       19.220000
75%       33.945000
max       66.500000
Name: avg, dtype: float64

In [18]:
prices.drop(columns="matched_name_in_auction",inplace=True)

In [22]:
batters['hs']=batters['hs'].str.replace("*","").astype(int)

In [23]:
batters.sample(3)

,pos,player,team,runs,mat,inns,no,hs,avg,bf,sr,100,50,4s,6s
54,55,Ayush Mhatre,CSK,201,6,6,0,73,33.50,113,177.87,0,2,20,12
64,65,Will Jacks,MI,139,7,7,2,46,27.80,76,182.89,0,0,12,9
63,64,Dewald Brevis,CSK,151,11,8,0,44,18.88,118,127.96,0,0,8,10

In [24]:
bowlers.sample(3)

,pos,player,team,wkts,mat,inns,ov,runs,bbi,avg,econ,sr,4w,5w
5,6,Eshan Malinga,SRH,20,15,15,54.2,507,32/4,25.35,9.33,16.30,1,0
69,70,Jaydev Unadkat,SRH,4,4,4,12.5,140,21/3,35.00,10.90,19.25,0,0
89,90,David Payne,SRH,2,2,2,5.0,70,35/2,35.00,14.00,15.00,0,0

In [25]:
prices.sample(3)

,player,auction_year,base_price,final_price,currency,auction_team,role
169,Yash Raj Punja,2026,3000000,3000000,INR,Rajasthan Royals,Uncapped
154,Tim Seifert,2026,15000000,15000000,INR,Kolkata Knight Riders,Capped
81,Mitchell Santner,2025,20000000,20000000,INR,Mumbai Indians,Capped

## 3.Feature Engineering

## 4.Data Analysis

### 4.1 Univariate Analysis

### 4.2 Bivariate Analysis

## 5.Justification

### 5.1 Batters

5.1.1 Capped

5.1.2 Uncapped

### 6.1 Bowlers

6.1.1 Capped

6.1.2 Uncapped